name: Build TrayCamera JAR
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build JAR
        run: ./gradlew buildExecutableJar
      - name: Upload JAR
        uses: actions/upload-artifact@v6
        with:
          name: traycamera-jar
          path: app/build/libs/TrayCamera.jar
          retention-days: 90
